# ==========================================
# Desktop Overrides (~/.config/i3/local.conf)
# ==========================================

# Daemons & Hardware Support
exec --no-startup-id /opt/urserver/urserver-start --no-manager --no-notify
exec --no-startup-id xrdb -merge ~/.Xresources
exec --no-startup-id solaar --window=hide

# MX Keys Mini / Function Key Media & Volume Fallbacks
bindsym $mod+F11 exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
bindsym $mod+F12 exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -5% && $refresh_i3status
bindsym $mod+Insert exec --no-startup-id /home/anthony/.local/bin/volumeup && $refresh_i3status
bindsym $mod+F6 exec --no-startup-id playerctl previous
bindsym $mod+F7 exec --no-startup-id playerctl next
bindsym $mod+F10 exec --no-startup-id playerctl play-pause

# Resolution Hotkeys
bindsym $mod+bracketleft exec res-4k-165
bindsym $mod+bracketright exec res-1440-165
bindsym $mod+shift+bracketleft exec res-1080-60
bindsym $mod+shift+bracketright exec res-1080-360

# Desktop-Specific App Launchers
bindsym $mod+b exec easyeffects
bindsym $mod+Shift+m exec --no-startup-id ~/.local/bin/kodi-presentation
bindsym $mod+j exec --no-startup-id ~/.config/i3/load_job_layout.sh
