# ==========================================
# Laptop Overrides (~/.config/i3/local.conf)
# ==========================================

# Screen brightness controls
bindsym XF86MonBrightnessUp exec brightnessctl set +10%
bindsym XF86MonBrightnessDown exec brightnessctl set 10%-
